### ISSUE TITLE
Errors while running docker-parfum

### ISSUE THREAD

**Issue by bqcuong** [tdurieux/docker-parfum#1]
Hi!

Thanks for the great repair tool.
I was not able to run docker-parfum due to some errors as below. Could you please help me to resolve them?

The simple Dockerfile content that I used to run with your tool:
```Dockerfile
FROM ubuntu:bionic
RUN groupadd -r test && useradd -r -g test test
```

When I tried to run with pre-installed docker-parfum with the following commands:
```bash
npm i -g @tdurieux/docker-parfum
docker-parfum repair Dockerfile
```

I got this error:
```bash
docker-parfum repair Dockerfile
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module 'diff'
Require stack:
- /usr/local/lib/node_modules/@tdurieux/docker-parfum/build/cli/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tdurieux/docker-parfum/build/cli/index.js:65:25)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@tdurieux/docker-parfum/build/cli/index.js'
  ]
}
```

Then I tried to run the tool with NodeJS API for the same Dockerfile (following the NodeJS code you provided in Readme), I got this error:
```bash
ts-node lib/run-parfum.ts
TypeError: node.$type.split(...).at is not a function
    at ShellParser.handleNode (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/lib/parser/docker-bash-parser.ts:171:63)
    at ShellParser.<anonymous> (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/lib/parser/docker-bash-parser.ts:876:19)
    at step (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-bash-parser.js:33:23)
    at Object.next (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-bash-parser.js:14:53)
    at /Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-bash-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-bash-parser.js:4:12)
    at ShellParser.parse (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-bash-parser.js:675:16)
    at DockerParser.<anonymous> (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/lib/parser/docker-parser.ts:209:47)
    at step (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-parser.js:33:23)
    at Object.next (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-parser.js:14:53)
    at /Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-parser.js:4:12)
    at DockerParser.parse (/Users/cuong/Research/docker-parfum/node_modules/@tdurieux/dinghy/build/parser/docker-parser.js:71:16)
    at /Users/cuong/Research/docker-parfum/lib/run-parfum.ts:8:34
    at step (/Users/cuong/Research/docker-parfum/lib/run-parfum.ts:33:23)
    at Object.next (/Users/cuong/Research/docker-parfum/lib/run-parfum.ts:14:53)
    at /Users/cuong/Research/docker-parfum/lib/run-parfum.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cuong/Research/docker-parfum/lib/run-parfum.ts:4:12)
    at run_parfum (/Users/cuong/Research/docker-parfum/lib/run-parfum.ts:5:42)
    at Object.<anonymous> (/Users/cuong/Research/docker-parfum/lib/run-parfum.ts:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at phase4 (/usr/local/lib/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/usr/local/lib/node_modules/ts-node/src/bin.ts:95:10)
    at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:800:3)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
FROM ubuntu:bionic

RUN groupadd -r mongodb && useradd -r -g mongodb mongodb
```

Thank you very much!

Best regards,
Cuong

**Comment by tdurieux** [comment]
Hello @bqcuong, I fixed the first bug, the second error that you faced is due to the version of nodejs that you are using. You need node >= 16.

**Comment by bqcuong** [comment]
Hi @tdurieux,
It is working now. Thanks a lot!
